### ISSUE TITLE
Crash when creating the aas file

### ISSUE THREAD

**Issue by mgerhardy** [PadWorld-Entertainment/bspc#3]
Report from discord about a crash when using the new version of wopbspc

**Comment by mgerhardy** [comment]
```
(gdb) bt
#0  0x000055555557ef7e in AAS_TraceClientBBox (start=0x7fffffffdc7c, end=0x7fffffffdc94, presencetype=4, passent=-1)
    at deps/botlib/be_aas_sample.c:575
#1  0x000055555556cdbb in AAS_GetJumpPadInfo (ent=59, areastart=0x7fffffffddf8, absmins=0x7fffffffddbc, absmaxs=0x7fffffffddb0, 
    velocity=0x7fffffffddc8) at deps/botlib/be_aas_reach.c:253
#2  0x000055555557955d in AAS_Reachability_JumpPad () at deps/botlib/be_aas_reach.c:3485
#3  0x000055555557d4bb in AAS_ContinueInitReachability (time=0) at deps/botlib/be_aas_reach.c:4730
#4  0x000055555556488f in AAS_CalcReachAndClusters (qf=0x55555e30b8e0) at be_aas_bspc.c:274
#5  0x0000555555585c1e in main (argc=3, argv=0x7fffffffe008) at bspc.c:543
(gdb) l
570			// start point of current line to test against node
571			VectorCopy(tstack_p->start, cur_start);
572			// end point of the current line to test against node
573			VectorCopy(tstack_p->end, cur_end);
574			// the current node plane
575			plane = &aasworld.planes[aasnode->planenum];
576	
577			switch (plane->type) { /*FIXME: wtf doesn't this work? obviously the axial node planes aren't always facing
578									  positive!!!
579									  //check for axial planes
(gdb) p aasworld.planes
$1 = (aas_plane_t *) 0x0
(gdb) p *aasnode
Cannot access memory at address 0xc

```
